// Builds the dashboard as one self-contained HTML file.
//
// The browser gets the same core modules used by Node: they are concatenated in
// dependency order, with `import`/`export` lines stripped, inside one function scope.
// Keep every import on a single line in src/core so this stays a simple text transform.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = (p) => fileURLToPath(new URL('../../' + p, import.meta.url));
const read = (p) => readFileSync(root(p), 'utf8');

const CORE_ORDER = [
  'src/core/dates.js',
  'src/core/format.js',
  'src/core/options.js',
  'src/core/names.js',
  'src/core/parse.js',
  'src/core/count.js',
  'src/core/stats.js',
  'src/core/analyze.js',
];

export function bundleCore() {
  return CORE_ORDER.map((file) => {
    const src = read(file)
      .replace(/^import .* from .*;\s*$/gm, '')
      .replace(/^export \{[^}]*\}(?: from .*)?;\s*$/gm, '')
      .replace(/^export \* from .*;\s*$/gm, '')
      .replace(/^export (?=(?:async )?function|const|let|class)/gm, '');
    return `// ---- ${file}\n${src}`;
  }).join('\n');
}

/**
 * @param {object} data  payload read by web/app.js:
 *   { mode: 'example', raw }                          the built website
 *   { mode: 'report', messages, options, source }     a report generated by the CLI
 */
export function buildHtml(data) {
  const json = JSON.stringify(data).replace(/</g, '\\u003c');
  const script = `(function () {\n'use strict';\n${bundleCore()}\n// ---- web/app.js\n${read('web/app.js')}\n})();`;
  return read('web/template.html')
    .replace('/* @@STYLE@@ */', () => read('web/style.css'))
    .replace('"@@DATA@@"', () => json)
    .replace('/* @@SCRIPT@@ */', () => script.replace(/<\/script/gi, '<\\/script'));
}

/** Payload for a CLI report: only what the dashboard needs, with names already resolved. */
export function reportPayload(result, source) {
  const messages = result.messages.map((m) => ({
    index: m.index,
    ts: m.ts,
    author: m.author,
    // Keep the text only where a number or a photo could be: the rest of the chat stays out of the file.
    text: m.author && (m.hasPhoto || /\d/.test(m.text)) ? m.text.slice(0, 120) : '',
    hasPhoto: m.hasPhoto,
    deleted: m.deleted,
  }));
  const { aliases, ...options } = result.options;
  return { mode: 'report', generatedAt: new Date().toISOString(), source, dateOrder: result.dateOrder, options, messages };
}
